POST http://localhost:4000/blog/like-blog
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhdEBnbWFpbC5jb20iLCJpZCI6IjY3OTYxNWQ0OTFlYmUzYWIwY2IwNWYyYyIsImlhdCI6MTczODE2MDMwOCwiZXhwIjoxNzM4MjQ2NzA4fQ.Ig7gQ9ppQ8_shSjDqWjPSXtooMpSHCWo9SX_46DR1Vk

{
  "_id": "67961a8091ebe3ab0cb05f3f",
  "isLikedByUser": "true"
}