POST http://localhost:4000/user/create-blog
Content-Type: application/json

{
  "title": "test title @ 3 134 # 4$ 123 asdas 12, ",
  "banner": "https://example.com/image-url",
  "des": "this is a short des",
  "content": {
    "blocks": [1, 2]
  },
  "tags": ["tag1", "tag2"]
}